coverage:
  status:
    project:
      default:
        # Keep visibility on overall coverage without blocking while the project
        # is ramping up toward a higher baseline.
        informational: true
    patch:
      default:
        target: 90%
        threshold: 1%

